### ISSUE TITLE
Language settings dropdown in backend services page is buggy

### ISSUE THREAD

**Issue by Foxi352** [smarthomeNG/smarthome#129]
The language settings dropdown in backend is broken since splitting the backend into multiple files (core, utils, blockly).

Choosing another language (english or french) works. But when returning to the service page the language dropdown always displays "German" as selected language. That also means that if you want to switch back from french or english to german the dropdown does not work because german is already selected. You then have to push the "reload" button to get back to german.

I did some debugging log and i think that in BackendCory.py, function services_html(self), the global translation_lang variable set in  utils.py function load_translation(language) is not available.

I seems to be a translation_lang variable scope problem.

**Comment by psilo909** [comment]
Just pushed a hotfix:
https://github.com/smarthomeNG/smarthome/commit/a39598615e5f27b80b3773cf28135f8ba7dd1aa6

reload should also work again.

not sure if my implementation is the best one (get_translation_lang function in utils.py). did not manged to access global variable from BackendCore otherwise.

please retest

**Comment by Foxi352** [comment]
I confirm this is working fine now, so i close my issue.
