### ISSUE TITLE
misbehavior while parsing an list attribute given as string with quotation marks

### ISSUE THREAD

**Issue by pfischi** [smarthomeNG/smarthome#143]
Following error occurred:

If an attribute value is given as list with quotation marks.

```atrribute_xxx = "val1 | val2 | val3" ```

the list contains following items

``` ['"val2', 'val2', 'val3"'] ``` (take a look at the wrongly added quotation marks).

An attribute without quotation marks, e.g.

```atrribute_xxx = val1 | val2 | val3```

is parsed correctly.

**Comment by ohinckel** [comment]
What would be the correct behaviour for this? One value with the whole string?

1. :white_check_mark: "test" -> "test"
2. :white_check_mark:  test -> "test"
3. :white_check_mark: test1 | test2 -> ["test1", "test2"]
4. :question: "test2 | test2" -> "test1 | test2"
5. :white_check_mark: "test1" | "test2" -> ["test1", "test2"]

**Comment by pfischi** [comment]
I would prefer ["test1", "test"] for 4. A pipe symbol should be treated as a string splitter in any cases.

**Comment by psilo909** [comment]
i prefer the solution above... " " would mean to me, that the inner part is a string. you cant give a e.g. name to an item with a | if you dont allow this

**Comment by psilo909** [comment]
or we introduce an escaping suich as \|. but i dont think newbies will get this..

**Comment by msinn** [comment]
I prefer the solution as outlined by ohinkel. 

It would be consistent with the handling of quotes in other configuration formats like json and yaml.

**Comment by bmxp** [comment]
If there are quotation marks then they should be obeyed. If this is standard for yaml I think it's consistent then as well. And I am pretty sure we will need some sort of escaping. Maybe we lend something from yaml syntax there as well.
[Here ](http://stackoverflow.com/questions/19176024/how-to-escape-special-characters-in-building-a-json-string) is something about JSON and [here](http://www.yaml.org/spec/1.2/spec.html#id2776092) about yaml. Since JSON is an official subset of YAML, and we might shift the whole config from these config files to YAML we just can manifest to adhere to YAML specifications.

**Comment by ohinckel** [comment]
I don't think we need escaping here and I prefer my solution(tm). My point of not needing escaping is, that it will not help here. The problems are the quotes in the resulting list. Escaping would not help here (maybe escaping the pipe could help a little bit, but will alos just result in a single string item):
* "test \| test" -> "test | test" (why do we need escaping here, spilling strings in the middle is just bad/wrong parsing which should be fixed)
* "test | test" -> "test | test" (shiuld just convert to a single string, since it is wuoted completely - nothing to split here)
* test | test -> ["test", "test"] (will be converted to list of strings)
* test | te\|st -> ["test", "te|st"] (if we realy need escaping this will be converted to list of strings)
* test \| test -> "test | test" (will be converted to a single string)

This would be my solution for this. Any further objections?

**Comment by pfischi** [comment]
@ohinckel 
That is the difference between bullet point 3 and 5? Just a typo?

**Comment by ohinckel** [comment]
@pfischi, the escaping character was missing in the comment (just used \ instead of \\\\). I updated the commet! Thanks for noticing.

**Comment by pfischi** [comment]
@ohinckel 

+1 for your approach.

**Comment by psilo909** [comment]
any conclusion? could need a decision for the "sma_em" plugin (to allow a list of serials to be provided as plugin attribute)

**Comment by msinn** [comment]
This happens because the conf-parser from mknx does check if the 1st and the last char are quotes. If so the parser removes them before interpreting the rest.

Should we change that behavior or just move on to yaml format?

**Comment by bmxp** [comment]
As conf is already marked as deprecated we should proceed with yaml format and leave it aside for conf. I do not see a necessity for riding a dead horse. We should drop conf support in 1.4 or 1.5 latestly anyway...

**Comment by psilo909** [comment]
ok 4 me. but for the feature im sma_em plugin mentioned above i will need to wait until then (as no one cried for it - an possibly i am the only one using the plugin, i don't mind)

**Comment by ohinckel** [comment]
@psilo909, it is possible to use `serial = abc | def` in the configuration, isn't it?

**Comment by ohinckel** [comment]
I prefer to drop `conf` support as soon as possible and stick to YAML.

In case we log warnings when users still using `conf` files it would be OK to drop it in the next release (1.4), if we do not log (what is the case AFAIS) we should add some warning logs about to migrate the configuration files to YAML in the next release (1.4) and drop support for `conf` later (1.5).

If we drop it now we do not need to fix the bug, if we drop it in 1.5 it's not worth to fix the bug (only for one release). I think we can close this.
