### ISSUE TITLE
Network Plugin Pull Status

### ISSUE THREAD

**Issue by patrickhener** [smarthomeNG/smarthome#156]
Network Plugin is just used to set Items via http: or tcp/udp. It would be useful to get Item Values from the Plugin as well. To set you use http://ip/item|path|value

It would be great to get the value by using http://ip/item|path|"get" or some other key word.

I tried to understand the source code of NW Plugin and failed miserably. Could someone clarify a way to approach the problem?

Please mark as feature request as well.

**Comment by onkelandy** [comment]
It would be great if the nw plugin would work much easier than right now. It's not possible to exchange values of items between two different smarthome instances without a logic and quite some trial and error. It also seems to be impossible to sync two items on two instances when "enforce_updates" is set to true. It's ping pong till eternity.... :(

**Comment by bmxp** [comment]
You should create a sync plugin where you can sync two (or more) SmartHomeNG instances and those should take special issues like enforce_updates into account. But beforehand you should ask yourself if you want a master/slave solution and if you simply hard-set the values (circumvening eval & Co.) or not.
Also if you want to use another instance as backup system which drops in when a failure of you master system happens?

**Comment by patrickhener** [comment]
Leaving this issue aside the nw plugin is still missing a "getValue" function. Maybe it would be state of the art to evolve the network Plugin to a REST API. I heard someone mentioning that in the forums.

**Comment by bmxp** [comment]
@cstrassburg wanted to implement a REST API, I have no info on how far that is. I also would not evolve the network plugin but create a new one with REST only.

**Comment by patrickhener** [comment]
Any Idea how I would contact @cstrassburg? KNX Forum? Not finding his username...

**Comment by bmxp** [comment]
Yes, he's cmalo in KNXUF

**Comment by ohinckel** [comment]
Hopefully @cstrassburg is responding faster in the forum than in this project. Am still waiting for feedback for other issues - but I have still hope!

I also tried to write a `bridge` Plugin to connect multiple instances to a network and broadcast changes of items (maybe other things too) to all nodes. But it is not yet finished due to the lack of time. And while developing it I thought "isn't it like the network plugin, just a little bit more?" - another reason stopping developing it further.

For the moment I think it would be a good idea to have read access to items using the network plugin, which could be used by external programs (not intended to connect multiple node via network, and I think the basic intention of this plugin was also not to connect multiple instances but be able to easily change values remotely, e.g. from external programs/systems).

The REST API would IMHO provide much more features than updating or reading item values.

**Comment by psilo909** [comment]
@ohinckel i wrote him an email some day ago, asking about his commitment to this project.

**Comment by patrickhener** [comment]
Otherwise I would start developing auf REST API which functions as the nw Plugin does. On this basis we  would be  able to expand it further easily.

**Comment by bmxp** [comment]
@cmalo: did you start steps towards REST API already?

**Comment by ohinckel** [comment]
@patrickhener, if you're using the develop version of SHNG you could try the [webservices](https://github.com/smarthomeNG/plugins/tree/develop/webservices) plugins.

**Comment by msinn** [comment]
Is something going on with this issue?

Should we close it or should I buy a  couple of birthday candles?

**Comment by bmxp** [comment]
We already have a working webservices plugin which should satisfy the needs. Feel free to reopen or create a new issue if this is not the case.
