### ISSUE TITLE
smartVISU and knxd 0.11.17 - spooky

### ISSUE THREAD

**Issue by geertge** [smarthomeNG/smarthome#190]
Hi, 

I installed the smarthomeNG pi image and I upgraded knxd to the latest version (0.11.17). If I connect with ETS 5 and I use the multicast mode I can send and receive telegrams. Everything is working fine. 

If I use smartVISU I get as status 0 (not the real status), no telegram will be send on the knx bus. It seem's I have no connection between smarthome/smartvisu and knxd.  Both are running on the same PI (IP 192.168.2.199).

And now the spooky thing:
I start an old PI with smarthome and knxd (IP 192.168.2.149) which connect to a NOT connected IP interface (192.168.1.102, not even in the same range), I change the IP address in the I/O connection on the new PI (192.168.2.199) to 192.168.2.149 (smarthome.py driver, IP address of the old PI, where knxd is connected to a not existing IP interface) and smartVISU WORKS.
What can be the problem and/or solution?

Geert

**Comment by bmxp** [comment]
Your statements above are hard to read. Please write short sentences and not monster ones.
You don't need SmartVISU if you want to work with SmartHomeNG. SmartHomeNG has a knx plugin which communicates with knxd or eibd.
It is however possible to use SmartVISU without SmartHomeNG and directly connect with a knx driver.
It is mandatory that you clarify what you really use.
To help you, please also provide also your configurations of knxd and possibly also you plugin.conf as far as it concerns the knx plugin. Also messages from SmartHomeNG in debug mode are valuable to have a look at.
In my opinion the far better place to get help is [knx user forum](https://knx-user-forum.de/forum/supportforen/smarthome-py). I will close the issue here as long as we get no further facts to do some research.
