### ISSUE TITLE
SML Plugin needs improvement for some smartmeters - users with SML smartmeter and plugintester needed

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#201]
The SML Plugin reads a number of bytes and starts after a timeout or buffer full with inspection of contents. Some smartmeters seem to send continuously data stream, repeating the data again and again. That leads to some readouts which have one of more data files in the buffer. Thus the first data block mostly is inspected fine but the following is incomplete.

To improve IMHO when need to 
- [ ] read data between start and end sequence (1b 1b 1b 1b) 
- [ ] generate checksum over data block and test with given checksum to ensure integrity
- [ ] end data read after the first successful readout to give the scheduler entry a chance

If you encounter the above described problem and have a smartmeter that gives incomplete readouts please  answer this Issue and provide useful data...

(original report https://knx-user-forum.de/forum/supportforen/smarthome-py/39119-sml-plugin-datenblock-gr%C3%B6%C3%9Fenfehler)

**Comment by bmxp** [comment]
I've created a Gist with log data: https://gist.github.com/bmxp/18379f0124fa7e039daddce1a50b70f3#file-sml-sample-log-txt
It's an Easymeter Q3BA1022 with IR readout head with USB, made by Udo from Volkszähler.

**Comment by ohinckel** [comment]
Implementing the complete SML protocol is a lot of work. That's why I only implemented parsing the relevant data (7-byte-value SML_ListEntry from SML_MessageGetListReponse).

But reading the data within a "1b 1b 1b 1b" block and checking the CRC could be an easy step before trying to parse the data.

Stop reading after an successful read may lead to buffer overflow of the reading device. I suggest to read all the data available and use the last data block for parsing the values.

**Comment by bmxp** [comment]
Since I assume that one intends to query the smartmeter nearby to specific points in time I would prefer to read the first data block with no error and report that back to the items. For sure it is a good idea to flush the buffer after doing that before closing the interface.
Maybe most people using the SML plugin will benefit from implementing the first step as you described just above, so I would implement that and put it to beta testing then.

**Comment by Bonze255** [comment]
could it be an other failure?
once i have 

> 2017-04-30  00:50:01 WARNING  Sml          Skipping unkown field 0x47
> 2017-04-30  00:50:01 WARNING  Sml          Can not parse entity at position 4225, byte 14: can't multiply sequence by non-int of type 'float': 77 07 01 00 01 08 01 ff 01 01 62 1e 52 ff 00 55 05 55 33 b6 01 77 07 b2 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00...

then 

> 2017-04-30  01:21:07 WARNING  Sml          Can not parse entity at position 4095, byte 9: unsupported operand type(s) for ** or pow(): 'int' and 'bytes': 77 07 81 81 c7 82 03 ff 01 00 01 01 01 04 48 41 47 01 77 07 01 00 00 00 09 ff 01 01 01 01 0b 06 48 41 47 01 07 54 de c2 97 01 77 07 01 00 01 08 00 ff 62 82 01 62 1e 52 ff 55 05 55 5f 20 01 77...
2017-04-30  01:21:07 WARNING  Sml          Can not parse entity at position 4158, byte 9: unsupported operand type(s) for ** or pow(): 'int' and 'bytes': 77 07 01 00 01 08 01 ff 01 00 01 62 1e 52 ff 55 05 55 38 10 01 77 07 01 00 01 08 02 ff 01 01 62 1e 52 ff 53 27 10 01 77 07 01 00 10 07 00 ff 01 01 62 1b 52 00 53 01 26 01 77 07 81 81 c7 82 05...

i think its also an type problem....

**Comment by ohinckel** [comment]
> 2017-04-30 00:50:01 WARNING Sml Skipping unkown field 0x47

The type 0x47 indicates a boolean value which has usually only one byte value and should be declared as 0x42 and not 0x47. Maybe this error happens since the data stream contains errors, or the parsing failed completely (e.g. when trying to parse entities while one byte shifted).

> 2017-04-30 00:50:01 WARNING Sml Can not parse entity at position 4225, byte 14: can't multiply sequence by non-int of type 'float': 77 07 01 00 01 08 01 ff 01 01 62 1e 52 ff 00 55 05 55 33 b6 01 77 07 b2 00 00 00 00 00 00 00 00 0...

This seems to be a reading error, since the end of stream contains too much `00` values. Do you have problem reading from your device? Maybe the cable is too long or the power supply too small?

> 2017-04-30 01:21:07 WARNING Sml Can not parse entity at position 4095, byte 9: unsupported operand type(s) for ** or pow(): 'int' and 'bytes': 77 07 81 81 c7 82 03 ff 01 00 01 01 01 04 48 48 41 47

Packet analysis: OBIS Code `81 81 c7 82 03 ff`,
* followed by `01` for `objName` (optional, empty)
* followed by `00` for `status` (optional, empty)
* followed by `01` for `valTime` (optional, empty)
* followed by `01` for `unit` (optional, empty)
* followed by `01` for `scaler` (optional, empty)
* followed by `04` for `value` (optional, 3 byte octet data `48 41 47`)

The expression to fail in [SML plugin](https://github.com/smarthomeNG/plugins/blob/042b451bbc04d650bd88ca48aade9bb46eb29c82/sml/__init__.py#L232) is
`entry['value'] * 10 ** entry['scaler'] if entry['scaler'] is not None else entry['value']`
But the `scaler` value should be `None` and no `pow` call should be done. Maybe the operator precedence is playing with us and rewriting the line to the following should clarify:
`(entry['value'] * 10 ** entry['scaler']) if entry['scaler'] is not None else entry['value']`

I start fixing some issues in the SML plugin and wrote some tests. If you want you can try by [branch](https://github.com/ohinckel/smarthomeNG-plugins/tree/issue-201).

To verify and be able to fix other problems please provide the SML data (logged in Debug mode). I'll take care to look into it and write some tests for this.

**Comment by gamade** [comment]
Hello,

some WARING lines from my log output for further diagnostics, as mentioned in the gitter.im chat:

`2017-09-14  02:08:38 WARNING  Sml_sml2     Can not parse entity at position 85863, byte 18: Try to read 5 bytes, but only have 4: 77 07 01 00 01 08 00 ff 64 00 01 00 01 62 1e 52 ff 56 00 01 bd 3b...
2017-09-14  05:03:38 WARNING  Sml_sml2     Can not parse entity at position 28472, byte 21: Try to read 49 bytes, but only have 4: 77 07 81 81 c7 82 05 ff 01 72 62 01 65 02 c8 ee a5 01 01 83 02 ba 66 6e 77...
2017-09-14  07:28:41 WARNING  Sml_sml1     Can not parse entity at position 56854, byte 13: Try to read 10 bytes, but only have 10: 77 07 01 00 00 00 09 ff 01 01 01 01 0b 09 01 45 4d 48 00 00 54 de 26...
2017-09-14  07:48:41 WARNING  Sml_sml1     Can not parse entity at position 69546, byte 15: Try to read 4 bytes, but only have 3: 77 07 01 00 10 07 00 ff 01 01 62 1b 52 ff 55 00 00 1f...
2017-09-14  11:48:45 WARNING  Sml_sml1     Can not parse entity at position 66971, byte 2: Try to read 6 bytes, but only have 6: 77 07 01 00 01 08 01 ff...
2017-09-14  14:58:46 WARNING  Sml_sml2     Can not parse entity at position 33092, byte 21: Try to read 49 bytes, but only have 2: 77 07 81 81 c7 82 05 ff 01 72 62 01 65 02 c9 7a 21 01 01 83 02 ba 66...
2017-09-14  16:28:47 WARNING  Sml_sml2     Can not parse entity at position 81234, byte 9: Try to read 3 bytes, but only have 2: 77 07 01 00 01 08 00 ff 64 00 02...`

**Comment by bmxp** [comment]
So @gamade provided this gist here: https://gist.github.com/gamade/da57b2661c2f8f1d5ba787cdd7f311b5
If you changed things I can cross check with my meter here as well. Let me know ...

**Comment by ohinckel** [comment]
This gist does not contain any error messages. Are they stripped off or is it working now?

**Comment by ohinckel** [comment]
I just updated by [branch](https://github.com/ohinckel/smarthomeNG-plugins/tree/issue-201), which includes some testing stuff and the new CRC16 check against the data packets received.

In case the plugin receives more data packets it will start from the end to analyse the data and extract the last complete data packet. After this it calculates the CRC16 checksum and verify it against the CRC16 in the data packet. If it fails a log message will be written and the previous data packet will be extracted from the data.

Please check if this works better since I don't know if the errors mentioned in knxuf is relating to this and I'm not able to reproduce this with my powermeter device.

In case everything goes well I'll create a PR.

**Comment by ohinckel** [comment]
Closing this issue since created PR is already merged and no negative feedback so far.
