### ISSUE TITLE
new function needed: has_iattr(item.conf, attrib) with attrib as list

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#212]
Ich würde gerne beim Smartplugin die Funktion has_iattr(item.conf, attrib) erweitern so daß man mehrere attrib übergeben kann, also als Liste. Hat das vielleicht schon jemand implementiert?

I would like to have a new function in smartplugin which will take a list of attributes instead a single one and that returns True if any of the listed attributes is defined in item.conf.

There are more possible way to do this:
- [ ] keep ``has_iattr(item.conf, attrib)`` but decide between argument attrib if it is a list or an array
- [ ] create a new function ``has_any_iattrs(item.conf, attriblist)`` (maybe another name)
- [ ] don't extend smartplugin but write a function in the module where is is needed, but this may lead to
      multiple implementations with the same goal

What would you prefer?

**Comment by ohinckel** [comment]
I don't like the `*_iattr_*` methods at all. I prefer a complely new config object which represents the configuration and providing simple methods e.g. `get_value`, `get_values`, `get_as_list`, `has_value`, etc. (see also my comment for commit  https://github.com/smarthomeNG/smarthome/commit/be0bcdbbe5ebb417abd102ef215760fda6e4053b).

For your suggestions I would vote for number 2: new method.

Going further we could also get rid of the `has_iattr` method completly: the `get_iattr_value` could simply return `None` in case the setting does not exists, otherwise it returns the value. This way the application can check if setting exists or not by checking the value for `None`. This would also save one extra call to `has_iattr` - which is in most cases used just before reading the actual value.

Having this, we could also have a method `get_iattr_values` which works like the method mentioned before but is getting a list of setting names and returns a `dict` with the setting name and value (also returning `None` for non existent keys).

This would be my suggestion, additionally wrapping all of this in a new config object. But the latter could be done in a second step.

**Comment by msinn** [comment]
@bmxp Unabhängig davon, dass die Funktion wie @ohinckel anmerkte nicht wirklich schön/intuitiv ist, wie hattest Du Dir

> Ich würde gerne beim Smartplugin die Funktion has_iattr(item.conf, attrib) erweitern so daß man mehrere attrib übergeben kann, also als Liste.

gedacht?

Soll das Ergebnis True sein, wenn ein Attribut der Liste vorhanden ist oder wenn alle Attribute vorhanden sind?

**Comment by bmxp** [comment]
True wenn ein Attribut der Liste vorhanden ist

**Comment by msinn** [comment]
@bmxp Items haben nun (Commit https://github.com/smarthomeNG/smarthome/commit/6a8f2ed51a4870bbf2511d1bb79519388cde94b4) ein neues Property 'attributes'.

Das Property ist eine Liste der Plugin-spezifischen Attributnamen (gemäß Inhalt des conf-dict) und r/o.

Deine Problemstellung kann damit folgendermaßen gelöst werden:
Als Ersatz für
```
result = has_iattr(item.conf, attrib)
```
kannst Du
```
result = attrib in item.property.attributes
```
nutzen.

Nun kannst Du über Algorithmen folgendes für eine Liste von Attributen (attrib_list) prüfen:

**Alle Attribute sind in dem Item definiert**
```
result =  all(elem in item.property.attributes  for elem in attrib_list)
```

**Mindestens ein Attribut ist in dem Item definiert**
```
result =  any(elem in item.property.attributes  for elem in attrib_list)
```

**Comment by bmxp** [comment]
Das schaue ich mir bei Gelegenheit genauer an, danke!

**Comment by bmxp** [comment]
Das schaue ich mir bei Gelegenheit genauer an, danke!

**Comment by bmxp** [comment]
Das schaue ich mir bei Gelegenheit genauer an, danke!

**Comment by bmxp** [comment]
Das schaue ich mir bei Gelegenheit genauer an, danke!

**Comment by msinn** [comment]
@bmxp Funktioniert das für Dich/Kannst Du damit leben?

Ich würde dann zu dem Thema einen Blog Eintrag verfassen und den Punkt hier schließen.

**Comment by bmxp** [comment]
Ich habe das für's knx plugin benötigt, unten im Webinterface.

Statt
```python
for item in self.items.return_items():
    if (self.plugin.has_iattr(item.conf, KNX_DPT) or self.plugin.has_iattr(item.conf, KNX_STATUS) or self.plugin.has_iattr(item.conf, KNX_SEND) or
        self.plugin.has_iattr(item.conf, KNX_REPLY) or self.plugin.has_iattr(item.conf, KNX_CACHE) or self.plugin.has_iattr(item.conf, KNX_INIT) or
        self.plugin.has_iattr(item.conf, KNX_LISTEN) or self.plugin.has_iattr(item.conf, KNX_POLL)):
        plgitems.append(item)
```

wäre es nun

```python
for item in self.items.return_items():
    result =  any(elem in item.property.attributes  for elem in [KNX_DPT,KNX_STATUS,KNX_SEND,KNX_REPLY,KNX_CACHE,KNX_INIT,KNX_LISTEN,KNX_POLL])
    if result:
        plgitems.append(item)
```

wobei man das natürlich noch weiter kürzen könnte...
