### ISSUE TITLE
print output in debug mode

### ISSUE THREAD

**Issue by kr2** [smarthomeNG/smarthome#213]
There are some print outputs, if one runs smarthome.py in debug mode with all loggers disabled.

```
./bin/smarthome.py -d
using python module ruamel.yaml version: 0.14.12

[27/Jun/2017:15:09:00] ENGINE Serving on http://192.168.2.4:8383
DomesticVentilation
```

**Comment by ohinckel** [comment]
> using python module ruamel.yaml version: 0.14.12

This is printed to show which version of `ruaml` is used. But I think this can be simply removed in [item_conversion.py](https://github.com/smarthomeNG/smarthome/blob/6e4a58062b54882b7aa65ce32f57911d9adcd88b/lib/item_conversion.py#L30).

The error message about the missing `ruaml` module (some lines later) should be still kept. It's not possible to write this into the log since the configuration for the logging is not loaded at this point.

> [27/Jun/2017:15:09:00] ENGINE Serving on http\://192.168.2.4:8383
DomesticVentilation

Comes from the `cherrypy` when starting the application (or mount). I think this could be change to log to the configured logger, but I did not check the documentation very much yet.

Does it only happen in debug mode?

**Comment by ohinckel** [comment]
> This is printed to show which version of ruaml is used. But I think this can be simply removed
> in item_conversion.py.

Removed in https://github.com/smarthomeNG/smarthome/commit/7d73158aa13e986df2302cd5b7d41fea6deb6643

**Comment by ohinckel** [comment]
> Comes from the cherrypy when starting the application (or mount).

Disabled screen logging in https://github.com/smarthomeNG/plugins/commit/017d25fd7c839edbc78c8809051e54f341da272b
