### ISSUE TITLE
Plugin dlms (develop) : exception, when no USB found

### ISSUE THREAD

**Issue by lgb-this** [smarthomeNG/smarthome#222]
I test a SmarthomeNG on a new Pi without the USB adapter for the communication with the DLMS. I get the following error:

```
2017-08-04  21:19:16 ERROR    Main         Plugin dlms exception: could not open port /dev/ttyUSB1: [Errno 2] No such file or directory: '/dev/ttyUSB1'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 275, in open
    self.fd = os.open(self.portstr, os.O_RDWR|os.O_NOCTTY|os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyUSB1'
```

Is it possible to catch such an error with an output in the logfile instead of an exception ?

**Comment by bmxp** [comment]
Yes, should be possible to catch that. I will habe to look at it.

**Comment by ohinckel** [comment]
Do we really need to catch all exceptions? I prefer to throw an exception in the plugin setup when it is currently not possible to use a plugin at all. This case is such an error since the device can not be opened and the plugin can not do anything without this device.

IMHO an exception is OK, If you just catch this and log another error you also need to take care about not reading from this uninitialized device in some scheduler tasks or other plugin logic, which will bloat up the complete plugin with some "is the plugin initialized correctly" checks.

**Comment by lgb-this** [comment]
I describe only my observation. It's up to the programmer, if he wants to enhance the error management system to help the user.

**Comment by bmxp** [comment]
The error should be caught with version 1.5 onwards. So I close this.
