### ISSUE TITLE
Backend / Start knxd

### ISSUE THREAD

**Issue by Foxi352** [smarthomeNG/smarthome#237]
Start' knxd service' and start 'knxd socket' buttons no longer work in the backend service overview.

 The path '/backend/start_knxd' was not found.

**Comment by bmxp** [comment]
This applies also to the other buttons except for cache checking. It seems to be just a path issue.

**Comment by msinn** [comment]
Nice to assign t to me, but I cannot test it. I don't use knxd. Lookingad the source code, I wood say the feature isn't there any more. I faintly remember that we decided to disable it some time ago, since it was not working.

**Comment by Foxi352** [comment]
Sorry, i understood from Gitter that it had to do with the http module changes (path e.t.c.) that's why i assigned it to you. I can't remember having read something about disabling this feature. But if so then we should just remove it from the html templates.

**Comment by msinn** [comment]
I checked with the v1.3 master. The html template does not show those buttons (since Developer Mode is off) and I could not find code in the backend plugin (v1.3 master) that would handle the buttons.

If I remember correctly, the removal had to do with the variety of ways the functionality hat to be implemented for different operation system version and the handling of different knxd versions and some people (including me) still using eibd.

If nobody wants to implement that code in a way that will work with all the variants, I would vote for removal of the buttons from the services page.

**Comment by msinn** [comment]
Since no one objected to the "wontfix" label, I close it.
