### ISSUE TITLE
HTTP module listens on wrong interface

### ISSUE THREAD

**Issue by ms276** [smarthomeNG/smarthome#258]
According to `modules/http/__init__.py`, the HTTP module listens on the interface which has a route to 10.10.10.10. See:

```
def _get_local_ip_address(self):
    import socket
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("10.10.10.10", 80))
    return s.getsockname()[0]
```

Usually that would be the default interface which in my case is the wrong one. I would expect for smarthome to either listen on every interface (0.0.0.0) or preferably take the address from a configuration file like it does for the port numbers.

**Comment by msinn** [comment]
It was changed to this listen on the IP address returned by _get_local_ip_address(), because the ip address was needed by some web interfaces of plugins. So listening on every interface (0.0.0.0) is not an option.

I could change the http module to use the configured ip address (if present) instead of _get_local_ip_address().

**Comment by ohinckel** [comment]
I suggest to introduce a global setting for smarthome which declares the IP to use.

This can be used for the http module or other things (eg the default IP for client plugin to listen).

This IP can be retrieved by the _get_local_ip_address().

**Comment by msinn** [comment]
@ms276 I have modified the http module. Now you can specify the ip address on which to listen. If you don't specify the ip address in etc/module.yaml, the module determines the ip address itself (just as before).

@ohinckel The global IP address is a good idea, but for a short fix I implemented the IP parameter in the http module. That is because the http module (or better some of the web interfaces) can't live with "listen on all ports" like other use-cases for the global ip address for listening would allow.

**Comment by msinn** [comment]
Feature made it to the v1.5 release
