### ISSUE TITLE
Database plugin: should return last valid value when no values found in timeframe query, not None

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#262]
There is one problem when using database queries together with a formula, etc. like
eval: sh.garten.ventile.ventil_3.SA.db('on', '12h')*720

As soon as there are no values in the query timeframe the plugin sends back a "None" and the equation results in an error: unsupported operand type(s) for *: 'NoneType' and 'int'

Of course this can be solved with an if/else but it would make more sense imho to solve it in the plugin. So it returns just "0" when no values are found in the requested timeframe.

**Comment by psilo909** [comment]
But a 0 would not be a correct answer in a mathematical sense...
Also a 9 could also lead to problems, e.g. when dividing through the database value :)

**Comment by onkelandy** [comment]
Well, actually you are right ;) The plugin should find the last value before the queried timeframe and give that value back, no?

**Comment by psilo909** [comment]
actually i think there already was a long discussion about this.. you dont know why there is no value.

if it did not change and therefore no new value was written, you are are right.

but if there are other reasons, like an outage of the sensor or too long time intervals between new values, it is also wrong.
in this scenario i would prefer the "if" statement to handle the situation explicitly.

**Comment by onkelandy** [comment]
There were a lot of discussions indeed ;)
Okay.. let's say it can be solved with an if / else, how would the else look like?

With an "on" query it's pretty simple but not with other queries..
eval: 0 if sh.ventil.SA.db('on', '12h') is None else sh.ventil.SA.db('on', '12h')*720

There needs to be a query to find the last valid entry in the database easily. Does that exist? The dbplugin.readLogs function could be helpful but I wouldn't know how to use it to get the last value of an item.

Speaking of that function.. The README talks about "deleting a value" in the readLogs section. Should rather be "read a value" ;) https://www.smarthomeng.de/user/plugins/database/README.html

**Comment by psilo909** [comment]
@onkelandy check my new webif for database plugin in develop branch.

you can set start and enddate and the method will return values starting from most recent one. if you extend the function we could also add a "limit" statement. i already told @ohinckel that we need a pagination with limit and offset for the function :)

**Comment by psilo909** [comment]
![gg](https://user-images.githubusercontent.com/15831643/39661151-499d36f6-504d-11e8-88be-8ecf26ad63b0.JPG)

**Comment by onkelandy** [comment]
Thanks for the info, looks cool. But doesn't solve the discussed issue or does it? A "lastvalue" function giving back the last value and timestamp would be perfect. Or do you mean the limit-thingy does that?

**Comment by psilo909** [comment]
partially.. it shows how to use readLogs with start and end time.. this way you could implement it by your own ;) or wait, until @ohinckel adds a limit parameter.

**Comment by onkelandy** [comment]
I still vote for an easy way to get the last value in the database in a specific timeframe with the value and timestamp as feedback. Something like
sh.item.db('lastvalue', start, end='now')
giving back the value

sh.item.db('lasttime', start, end='now')
giving back the datetime of last value

Don't you think that would make things easier? 
Let's say I want to calculate the average temperature of the hour one hour ago but nothing was written in the db there. Then you could use a logic like 
sh.item.db('lastvalue') if sh.item.db('lasttime', '2h', '1h') > datetime.datetime.now() - datetime.timedelta(hours = 2) else sh.item.db('avg', '2h', '1h')

**Comment by onkelandy** [comment]
I am actually quite confused now.. I'm querying the values of an item in a timeframe where no values have been written (checked in the MySQL database).

When I query that via a logic:
logger.info(sh.garten.ventile.ventil_8.SA.db('on', '5h', '4h'))

I get 0.00 as a result. What is actually perfectly fine. But in the eval statement I always got a "None" when no value was found in that timeframe..?

**Comment by onkelandy** [comment]
I'm also wondering how this error can happen.. any idea?
WARNING  lib.item     Item garten.ventile.ventil_2.laufzeit_1w: problem evaluating 0 if sh.garten.ventile.ventil_2.SA.db('on', '1w') is None else sh.garten.ventile.ventil_2.SA.db('on', '1w')*10080: unsupported operand type(s) for *: 'NoneType' and 'int'

**Comment by ohinckel** [comment]
> I'm also wondering how this error can happen.. any idea?

Do you often get this error? I could only imagine that this happens when the value is just written to the database between the first access to the item to check the value and the second access to the item for calculation.

> or wait, until @ohinckel adds a limit parameter.

The reason for not having a limit parameter is, that the SQL statements differs for each database system. And I guess querying all the data for just fetching the first row will have bad performance.

**Comment by onkelandy** [comment]
I've changed the eval code slightly and it seems to work now. I guess ;) Maybe it is also because something was written in the database for the queried timeframe.

Anyhow, what do you think about adding those two query methods:
sh.item.db('lastvalue', start, end='now')
giving back the last value in the specified timeframe

sh.item.db('lasttime', start, end='now')
giving back the datetime of last value

This would make queries much more reliable and usable. Maybe it can be generalized even better - it was just a first idea ;)

**Comment by ohinckel** [comment]
> sh.item.db('lastvalue', start, end='now')
> sh.item.db('lasttime', start, end='now')

At least this way you have to specify a time range (like for the other queries) too. But still it could be time and resource consuming since there's no generic way of limiting the result set in SQL to let the server do the work and only return the required row. This means the client has to fetch some (maybe all) data (depending on the driver implementation) but only fetch one row (e.g. by using `fetchone()`). Querying the last value for `start=0` and `end=now` would tell the server to read all the data - even if only the last row is fetched.

One other thing with the suggestion solution is, that we introduce a different return value. Usually you will get some data depending on the item's value. But now we also return value of the item's lastchange value.

And how is this all with the other implementations (SQLite and RRD plugin)? Should we start to drop support for it? I don't know how often RRD is used but SQLite is also supported by the database plugin. We should decide this before starting to introduce different query methods for item values (or data) which is only supported by one of these plugins.

**Comment by onkelandy** [comment]
The most useful scenario to get the "last valid value" is in a standard query I guess. So I want to know the average from yesterday between 5 and 6 o'clock. If there is no data written in that timeframe it is most likely the value stayed the same as before 5. To get a value from a totally empty range might be tough.. 

But let's assume there is one value written at 5.55. Couldn't the (at least SQL) query look up the previous row to calculate everything from 5 to 5.55?

Dropping SQLite would be sad but if it's necessary or useful why not. Then there is a separate plugin for each database like, influx, sqlite, sql,..?

**Comment by ohinckel** [comment]
> If there is no data written in that timeframe it is most likely the value stayed the same as before 5.

Can you provide an example? The log table and the SQL statement (logged in DEBUG mode) when fechting data for a given item, would be helpful.

> Dropping SQLite would be sad but if it's necessary or useful why not. Then there is a separate plugin for each database like, influx, sqlite, sql,..?

Maybe you got it wrong: the database plugin will not drop any support. Instead we should drop the other plugins (especially `sqlite` and `rrd` - don't know how's maintaining this). If we only have one plugin which provides data to visu we can change or extend the signature (of the `series()` method). But currently we can't since we need to update all of these plugins providing data support for visu.

**Comment by msinn** [comment]
I am in favor of dropping the sqlite plugin. But I think we need a migration tool to the database plugin, so users don't loose the data they collected. I don't know, if someone still uses the rrd plugin. At least no one so far checkt the rrd line in the questionnaire about usage of classic plugins.

**Comment by ohinckel** [comment]
You're right, the last query will not return a value since both values in the database have a duration set. This means that the given value for the given row was only between the `time` and `time + duration`. The query is selecting for the a time range which is after `1535537080345 + 243397`. So there's no value in the database available.

The last value will be returned in case the duration is still `NULL`. This means that the value was not changed until `now`. These values are included in the result, but the values having a duration set (which is not in the time range) will not be included. Only in case they match the selected time range.

**Comment by onkelandy** [comment]
Thanks, totally understood. What about this solution:
first query if a value is between two timestamps.
- if yes do the normal thingy as above
- if no, select all timestamps from given item until the start query time and get the value from the last result of that query

Short test didn't show any performance issues.

**Comment by smaiLee** [comment]
As discussed earlier I think this would not be correct. A value which ends before queried start time (terminated by duration) is not valid at this point in time and should not be returned.

**Comment by onkelandy** [comment]
totally true. it should only be considered if starting time of that "previous value" + its duration > query_starttime or even query_endtime.

**Comment by onkelandy** [comment]
Oh I see.. maybe there was a problem with the duration entry in my case.. I'll have a closer look.
Does the dump in the stop procedure write the duration from the last change until now (clean shutdown of smarthome) in the database?

**Comment by ohinckel** [comment]
> Does the dump in the stop procedure write the duration

Yes, when shutting down, the duration will be set because SHNG assumes that the value was until the shutdown. Which values will be there after the shutdown is unknown. So it set's the duration to `now` on shutdown.

Maybe it would an idea to create a new log entry when SHNG starts up without a duration?

**Comment by onkelandy** [comment]
I guess that's a pretty good idea! 
I'm not sure if that is connected with my "None" result problems but I'm gonna do an intensive debug log checking the next days and have a look.

Thanks so far!

**Comment by onkelandy** [comment]
The init function works differently on purpose. It's also available for cache and knx. Meaning that when it's set to init, the item gets initialized by the cache value. Same for the database. So best thing would be to write to database after plugin init no matter what the config is. If its set to "init" the value gets read from the db and written with a new timestamp. If its "yes" the value gets loaded in a different way (knx, cache) and after that written with the current timestamp into the database.

What do you think? "Only" challenge is to be sure to write the value only after it is properly initialized.

**Comment by ohinckel** [comment]
To be honest, it doesn't matter what other plugins do. The implementation for `init` or `yes` depends on plugin and is not handled in a general way in SHNG (core).

>  If its "yes" the value gets loaded in a different way (knx, cache) and after that written with the current timestamp into the database.

This is already implemented. Changes to values will be written to the database with their durations.

>  If its set to "init" the value gets read from the db and written with a new timestamp.

This is also implemented, except that the timestamp is the lastchange time and not `now`. I think this is a bug because lastchange is the time where SHNG was shutdown. Using this assumes that SHNG know that the value for the items did not changed while SHNG was not running - but it can't be right, SHNG is not a miracle :)

I'll fix this by replacing the [existing code](https://github.com/smarthomeNG/plugins/blob/develop/database/__init__.py#L124)
```python
  self._buffer_insert(item, [(last_change_ts, None, value)])
```
with something like:

```python
  self._buffer_insert(item, [(now_ts, None, value)])
```

**Comment by onkelandy** [comment]
Yep, what I've written above was bullshit anyhow and not true ;)
Thanks, I guess so far we have covered all the problems of this issue, right?

Could my initially described problem of receiving a "None" when using the eval but a correct value when using a logic be the result of the smarthomeNG startup process? Somehow that the plugin wasn't fully initialized when the eval was triggered or whatever? If it wasn't initialized I would get a different error like "foo.db does not exist" I guess..?

**Comment by ohinckel** [comment]
Currently there is a `self.logger.debug()` line in the `parse_item()` method of the plugin. So running SHNG in debug mode should tell you what is executed in which order.

To sum this issue up: the lastchange value should be replaced with the current time as mentioned in my [previous comment](https://github.com/smarthomeNG/smarthome/issues/262#issuecomment-418447694). I'll implement this and close this issue then.

**Comment by ohinckel** [comment]
Issue with the timestamp was fixed a month ago. Closing this now.

**Comment by onkelandy** [comment]
Means that now with every new start current value at current time is written into the database? Without the database: init setting?
