### ISSUE TITLE
Make baseurl in lib.network.Http a real baseurl instead of just a default

### ISSUE THREAD

**Issue by smaiLee** [smarthomeNG/smarthome#269]
The baseurl argument is somehow misleading. Commonly a baseurl is something that is used to make a relative URL absolute, but in lib.network.Http it is just a default URL.

I would prefer the following behavior: If a baseurl is set, the passed URL of member functions should be added to the baseurl.
Example:
```python
http = Http('http://my.server/')
http.get_json(url='path')
```
This should result in a call to _http://my.server/path_ (currently it results in _path_, the baseurl is ignored if the argument is set).

**Comment by Foxi352** [comment]
The lib is currently under heavy development (because i use it in a new Philips TV plugin and add features as i need them).

I think i get your point. The name was indeed not carefully chosen. In the current implementation it is not a base url but more a default url. That means it uses the baseurl only if you don't pass any url as parameter.

I think your idea will work, because basically i can think of 3 different scenarios:

1. You only use a single url in the instance and thus only set 'baseurl' and leave `url` empty on requests.
2. You use the same server and put it into `baseurl` and pass the different paths as `url` parameter on requests
3. You use completely different servers and just leave `baseurl` empty and pass the full `url`'s as parameter in requests

I think that is what you mean ?

**Comment by smaiLee** [comment]
That's exactly what I mean.
I was trying scenario 2 in influxdb Plugin. There you have a Server and different pathes for querying and writing.

Actually I don't use the module anymore, as influx needs POST method in some cases. But perhaps someone else could use this as well.

**Comment by Foxi352** [comment]
I will change this in next push, that makes sense.
FYI: There is a `post_json` method ...

**Comment by smaiLee** [comment]
Thanks, I've seen this. But I need a combination of POST and URL-Parameters and additinally influx has uncommon HTTP status 204 with no content which means that writing was OK.
