### ISSUE TITLE
Feature request: rollover logs at restart

### ISSUE THREAD

**Issue by henfri** [smarthomeNG/smarthome#301]
Hello,

when trying somthing out, I often make mistakes. Then it is useful, if the log file starts at sh.py start.
I think this is possible with the timerotating Handler (https://docs.python.org/3/library/logging.handlers.html#logging.handlers.TimedRotatingFileHandler.doRollover) by calling the doRollover method at sh.py start.

Would this be possible?

Regards,
Hendrik

**Comment by msinn** [comment]
Would you have that behavior for all filehandlers you defined in etc/logging.yaml or should it only be done for a single handler? (I have 6 filehandlers defined and don't know what would be the better solution)

How would you enable/disable the **rollover logs at restart** feature?

**Comment by henfri** [comment]
Hello,

I could imagine:
 version: 1
 disable_existing_loggers: False
 global_rollover_at_start: False
 handlers:
   file:
     class: logging.handlers.TimedRotatingFileHandler
     level: DEBUG
     formatter: detail
     when: midnight
     backupCount: 7
     filename: ./var/log/smarthome.log
     rollover_at_start: True


This would allow both.
But it would be sufficient for me to make this global.

Greetings,
Hendrik

**Comment by msinn** [comment]
This won't work. The structure of the logging.yaml file is mainly defined by Python (and not SmartHomeNG). Adding a key (rollover_at_start) to handlers will crush the Python logging system.

Please encode yaml code as code in future postings. Otherwise it is hard to read.

**Comment by henfri** [comment]
So, why not make the rollover at start default and not-configurable?

**Comment by msinn** [comment]
Because not everybody would like that behavior. As far as I know, you are the only one who wants it.

If it would be configurable, everybody could have it his own way. If the rollover was forced everybody would have to have it your way.

By the way, as I wrote in #337, the logging system is configured directly from /etc/logging.yaml. SmartHomeNG doesn't know at startup which Loggers are configured or used, so it can not simply force a rollover. Do call the DoRollover() Method, there has to be an instance of the logger object first.

Why don't you just do the rollover in a start script for SmartHomeNG?

**Comment by bmxp** [comment]
@henfri you might want to change the logging oder to logbook and raise a PR. Otherwise a start script to do the rollover manually would be the way to go.
