### ISSUE TITLE
New Logfiles at Startup

### ISSUE THREAD

**Issue by henfri** [smarthomeNG/smarthome#337]
Hello,

RotatingFileHandler supports doRollover(). I suggest to call this function on sh.py start. 
This would help debugging, as a new file is created on sh.py restart

Regards,
Hendrik

**Comment by msinn** [comment]
SmartHomeNG configures the Python Logging system by handing the content of /etc/logging.yaml directly to the function ```logging.config.dictConfig()```. SmartHomeNG doesn't know or care which loggers exist or how they are configured.

If the Rollover ist supported by ```logging.config.dictConfig()```, you could configure it in /etc/logging.yaml. Otherwise you are out of luck.

**Comment by msinn** [comment]
By the Way: Is this your Christmas issue? You brought it up last Christmas already (#301). I testet it then and found, that it is not configurable through ```logging.config.dictConfig()```.

**Comment by henfri** [comment]
Hi,

that's funny. I did not remember that!

Greetings,
Hendrik
