### ISSUE TITLE
cpuusage tool: exception thrown on shng stop

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#376]
line 103 shng_pid = get_pid() leads to an uncatched exception as the PID can not be found anymore. I'm not sure whether it is better to delete line 103 and 104 or to use another try/except.

Easy to fix anyhow ;) Thx!

**Comment by msinn** [comment]
Those lines are there to catch the problem to get information after a restart of shng. If you would delete then, you would get an exception every time shng restarts. Now you get an exception once in a while. Just to try/except those lines would not help either, since the information is needed. A routine that waits for the new pid file has to be implemented. I put it on the list for v1.9.
