### ISSUE TITLE
eval expression with "value" not working correctly on init

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#449]
Item:
```
    triggertest3:
        type: num
        cache: true
        eval: value + 1
        crontab: init = 0
```

Error:
```
Jan 03 11:45:18 CET NOTICE   lib.smarthome     Main         --------------------   SmartHomeNG initialization finished   --------------------  --  (smarthome.py:start:638)
...
Jan 03 11:45:25 CET WARNING  lib.item.item     test.triggertest3-eval Item test.triggertest3: problem evaluating 'value + 1': can only concatenate str (not "int") to str  --  (item.py:__run_eval:1290)
```

If triggered manually, everything is fine. However, when triggered by crontab init (even with delay) "value" seems to be handled as string instead of the actual (default or cached) value of the item.

**Comment by msinn** [comment]
For me the item definition makes no sense. You define cache to be true, only to overwrite the cached value afterwards with crontab: init

The problem rises, because you define a vale to be set on **conteb: init**. which is a string by default.
When evaluating the eval expression, **value** is not the item's value any more. It is the string value following **init =**
So the eval tries to do the following: eval('0'+1)


As a (quick)-fix the eval statement will be retried with ``value = float(value)`` to convert the init String to a number.
(is pushed to develop)

**Comment by onkelandy** [comment]
OIC.. I expected the problem originating from something completely different ;)
Thanks, the fix works fine.


And yes, you are right, the cache doesn't make too much sense hehe.

**Comment by msinn** [comment]
It has to be fixed in a more general way, because it isn't an init/number issue.
It is an issue for scheduler attributes (cron, cycle) which are setting a value. Bool values, e.g. would still (line ``crontab: sunrise = False``) produce an error.
