### ISSUE TITLE
New Plugin Multi-Instance System: get_instance_name() not available in __init__ method of plugin

### ISSUE THREAD

**Issue by psilo909** [smarthomeNG/smarthome#56]
Currently, it seems that instance specific information is not available in the plugin specific init-method. This is a problem as e.g. plugin-specific subthreads (as the CallMonitor in AVM) can be created in the init-method and need these information. 

i think the behaviour is bound to PluginWrapper, where init is called before setting the instance name

```
class PluginWrapper(threading.Thread):
    def __init__(self, smarthome, name, classname, classpath, args, instance):
        threading.Thread.__init__(self, name=name)
        exec("import {0}".format(classpath))
        exec("self.plugin = {0}.{1}(smarthome{2})".format(classpath, classname, args))
        setattr(smarthome, self.name, self.plugin)
        if isinstance(self.get_implementation(), SmartPlugin):
            if instance != '':
                logger.debug("set plugin {0} instance to {1}".format(name, instance ))
                self.get_implementation().set_instance_name(instance)
            self.get_implementation().set_sh(smarthome)
```

**Comment by psilo909** [comment]
i rewrote my plugin to use the information from run method only.
anyway, i still think its not perfect that the information is only available outside the __init__ method.

**Comment by cstrassburg** [comment]
i changed the plugin creation mechanism to set the instance name before call the __init__ method. please test it. 

smartpugin uses now multiple inheritance to get the methods from Utils.py 
now you can call self.is_float(...)

**Comment by cstrassburg** [comment]
an other issue: I can create for every plugin config attribute implicit a member inside the plugin object. 
``` 
[plugin1]
   class_name = foo
   class_path = plugins.bla
   test = test1
   foo = bar 
   bar = foo
``` 
and inside the plugin you can get the values with ` self.foo ` or `self.test`
could it be useful?

**Comment by psilo909** [comment]
my issue can be closed, keeping this open die to last question of cstrassburg.

from my point of view, this could be useful yes. but init with params should be kept alive due to backward compatibility

**Comment by cstrassburg** [comment]
thanks for the pr, but binding a whole item is not  fine enough. If you use two 1-wire and knx plugins and bind a knx and 1-wire to the item your solution does not work.

**Comment by cstrassburg** [comment]
become obsolete by plugin multi instance implementation

**Comment by ohinckel** [comment]
> from my point of view, this could be useful yes. but init with params should be kept alive due to
> backward compatibility

Just a few notes no plugin parameters: I was thinking about to change the signature completely for the `init` method: having just one `args` argument containing a `dict` with all configured parameters (see also #27).

Putting all parameters directly into member fields may be a bad idea since it could overwrite fields without notice (one could accidentally overwrite a field which is not a configuration parameter but an internal variable which should not be change from outside). And the plugin should take care explicitly which parameter it is using and which not.

@cstrassburg, since the first problem about the instance name is solved already we could close this issue and talk about the plugin parameter handling in #27.

What do you think?
