### ISSUE TITLE
Digits at item names first character should be considered as bug.

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#63]
Please generate an error when a digit is encountered in an item parsing.
e.g. item names [1w_Bus], [42] or [_Bus] 

Maybe also item names like [and], [class], [def] etc. should be avoided, since they are reserved python names.

**Comment by bmxp** [comment]
I just fixed it. Please check it out and close if you find so, too.

**Comment by ohinckel** [comment]
I'll close this, since it was implemented in https://github.com/smarthomeNG/smarthome/commit/a1a08cf233858b8946bcc8b46a1a53d91c378d1e and release with 1.2 already.

Still I'm a little bit unhappy about this implementation since it
a) completely reject items starting with a digit (even if you don't use ith with `sh.some.path.to.<digit>`) and
b) it rejects it for all configuration files (e.g. also for `plugin.conf` or `logic.conf`).

I would just write a warning into the log when an item is using digits as first character. It should not break since you will still be able to find/access it using some other methods (like `sh.return_item(...)`).

In all other cases it is OK to have names starting with a digit.
