### ISSUE TITLE
feature request: multiclick for items

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#77]
Only some small adaptions seem to be necessary to create a multiclick option for KNX switches:
https://knx-user-forum.de/forum/supportforen/smarthome-py/36050-taster-doppelklick-via-logik

Would love to see this implemented in item.py

**Comment by onkelandy** [comment]
@cstrassburg
Is there already somerhing on the way? My old hack doesnt seem to work anymore :(

**Comment by onkelandy** [comment]
Any news on such a feature? What about uncommenting the current solution. It actually works fine. Not the perfect solution but working. Or is it not necessary anymore to achieve a multiclick implementation? @psilo909 I guess you've implemented but commented out the few code snippets, right..?

**Comment by msinn** [comment]
The title of the issue is misleading, I think.

It ist not about implementing a multiclick feature in the item object but about implementing another age-method (**prev_update_age()**) analog to the new **update_age()** which has been implemented for the **on_up_date** item-attribute.

I think the new method can be added. I am not sure if I'll do it for the v1.4 release...

> What about uncommenting the current solution.

Not as ist is. It is not initializing the object attributes  properly. Needs at least some refinement

Btw.: Implementing a "multiclick" feature for items won't happen. You just can't click items. (or have you ever tried to click a temperature? :wink: )

**Comment by msinn** [comment]
prev_update_age has been implemented in v1.4

**Comment by onkelandy** [comment]
Yep perfect.. Seems like everything is working as before without the need of uncommenting ;)
Maybe I'll write some short eval / logic example on how to use it. 

How is the documentation going to be handled in general? With the old mknx smarthome.py github Wiki, the smarthomeNG wiki and the website some installation manuals and examples are spread apart quite alot.

**Comment by msinn** [comment]
The structured documentation is going to be on the website only. I started to flag Wiki pages as outdated (with a link do the webite's documentation).

The documentation is part of the github repo and written in rST (or parts in markdown). For people w/o github & rST knowledge, there are feedback pages for the documentations within the wiki. They can create a wiki page with new content and leave a comment in the appropriate feedback page.
